AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: And example of a simple instrumented Python Lambda
Parameters:
  NRAccountId:
    Type: String
    Description: Your New Relic account ID; necessary for distributed tracing.
    AllowedPattern: '[0-9]+'
Resources:
  NewRelicExample:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://nr-test-saket-layers-us-west-2/f21285a6bcb45b5b94e05be2f72b2d05
      Description: A simple Lambda, with New Relic telemetry
      FunctionName: newrelic-example-python
      Handler: newrelic_lambda_wrapper.handler
      Runtime: python3.10
      PackageType: Zip
      Environment:
        Variables:
          NEW_RELIC_LAMBDA_HANDLER: app.lambda_handler
          NEW_RELIC_ACCOUNT_ID:
            Fn::Sub: ${NRAccountId}
          NEW_RELIC_DATA_COLLECTION_TIMEOUT: 30s
          NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS: true
      Layers:
      - Fn::Sub: arn:${AWS::Partition}:lambda:${AWS::Region}:451483290750:layer:NewRelicPython310:1
      Policies:
      - AWSSecretsManagerGetSecretValuePolicy:
          SecretArn:
            Fn::ImportValue: NewRelicLicenseKeySecret-NewRelic-LicenseKeySecretARN
    Metadata:
      SamResourceId: NewRelicExample
  Logs:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
        - ''
        - - /aws/lambda/
          - Ref: NewRelicExample
      RetentionInDays: 7
    Metadata:
      SamResourceId: Logs
